apiVersion: v1
kind: Namespace
metadata:
  name: stg
  labels:
    name: stg
---
apiVersion: v1
kind: Service
metadata:
  name: flaskapp-deployment
  labels:
    app: flask-svc
  namespace: stg
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
  - port: 5005
    protocol: TCP
    targetPort: 5005
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-flask-svc
  namespace: stg
spec:
  defaultBackend:
    service:
      name: flask-svc
      port:
        number: 5005
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-app-configmap
  namespace: stg
data:
  DEBUG: "True"
 
  FLASK_APP: "run.py"
  FLASK_DEBUG: "True"
  
  SERVER_ADDRESS: "http://localhost:5005/"
---
apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
  namespace: stg
type: Opaque
data:
  STRIPE_SECRET_KEY : c2tfdGVzdF81MVAwbUlOQms1NnRxRVp3YzlrSU9tYkREQUNIQVQ4d1g3T1ZlWnd3SVVkWG1rMndDMXdWSU1qY29vSnRYQWFGSjdOd3RaTlg1bllvMFVpQXQ4MmEwT3FvaTAwS2tiWjNuT3M=
  STRIPE_PUBLISHABLE_KEY : cGtfdGVzdF81MVAwbUlOQms1NnRxRVp3Y3FvMlNCZG9mNGRxZGg2SVdsN1VFODQyT0RtazBNdXFpUXlLdnJpb2NQMjlqc3F1bGRZYXJKbG1iSkpYNUh1YkhrUXdVV3FVRzAwQ1F4TWExUUY=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-deployment
  labels:
    app: flaskapp-deployment
  namespace: stg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        imagePullPolicy: IfNotPresent
        image: ecomme7:beta
        ports:
          - containerPort: 5005
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 450m
        envFrom:
        
        - secretRef:
            name: stripe-secret
        
        - configMapRef:
            name: flask-app-configmap
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-flaskapp
  namespace: stg
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flaskapp-deployment
  minReplicas: 3
  maxReplicas: 50
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 5
      - type: Pods
        value: 4
        periodSeconds: 5
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 10
      policies:
      - type: Percent
        value: 50
        periodSeconds: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
status:
  observedGeneration: 1
  currentReplicas: 1
  desiredReplicas: 1
  currentMetrics:
  - type: Resource
    resource:
      name: cpu
      current:
        averageUtilization: 0
        averageValue: 0
